### ISSUE TITLE
Separate conda package in two

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#168]
#### Description
Currently, the conda package contains the python code and the Khiops binaries. This makes building times very long as it recompiles khiops for each python version even though it is not necessary. Separating the binaries would speed up the tests and the release procedure.

#### Questions/Ideas
- Separate into the packages:
  - `khiops-core`: binaries 4 variants (Windows, Linux, Mac and Mac ARM)
  - `khiops`: python package depends on `khiops-core`
- This is more coherent with the current organization since a pure conda release would belong to the `khiops` CI.

**Comment by popescu-v** [comment]
Yes, the `khiops-core` package would be pushed to the relevant Conda channels (dev or release) and "pulled" by the `khiops` (-python) Conda package upon install, as a dependency.

Thus, instead of using the Git tag of the `khiops` repository for controlling which version of the Khiops binaries will be used, we would use the relevant version of the `khiops-core` package. This entails the minor hassle of making sure a relevant version of the `khiops-core` package (sometimes based on the `dev` branch of the Khiops Git repository) is pushed to the `khiops-dev` Conda channel.

**Comment by folmos-at-orange** [comment]
Further simplifications: The `LearningTest` infra will only test 2 conda packages (Linux and Windows).

**Comment by sgouache** [comment]
Great initiative!
But are you sure we won't end up having NxM khiops-core packages ?
(N=number_of_os_versions, M=number_of_python_versions)
See [ref](https://github.com/KhiopsML/khiops-python/blob/dev/packaging/conda/conda_build_config.yaml)

**Comment by folmos-at-orange** [comment]
> Great initiative! But are you sure we won't end up having NxM khiops-core packages ? (N=number_of_os_versions, M=number_of_python_versions) See [ref](https://github.com/KhiopsML/khiops-python/blob/dev/packaging/conda/conda_build_config.yaml)

This should resolve the issue of having to test different "python versions" for binaries that do not use any of the Python API.

**Comment by sgouache** [comment]
I know we're not testing any python. What I'm concerned about is the availability of the MPI(CH) shared library for each python version.
As we've experienced, depending on the chosen channel, not all python versions have the same MPICH versions available.
Unless we can depend on a MPI conda package that is "variant-free", I guess it will look like:

- No MPI => no khiops-core
- Different MPI => different khiops-core behavior so we likely have to test each arch x python_version
