### ISSUE TITLE
Add deprecation warnings for removals in Khiops V11

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#176]
#### Description
Some features will be removed in Khiops V11, we should alert from the next minor releases of `khiops-python` of their future removal.

#### Questions/Ideas
- The list will be available here: https://github.com/KhiopsML/khiops/issues/223
- Make a list with MB with any remaining deprecations.

**Comment by folmos-at-orange** [comment]
Deprecation list
- `discretization_method`:
  - Values `EqualWidth` and `EqualFrequency` deprecated for supervised learning
- `grouping_method`:
  - Values `BasicGrouping` deprecated for supervised learning
- `min_group_frequency`
- `min_interval_frequency`
- `max_groups`
  - replaced by `max_parts`
- `max_intervals`
  - replaced by `max_parts`
- `results_dir`: Is deprecated without message because it is mandatory and it will be renamed to `report_file_path`
- `results_prefix`
  - replaced by `report_file_path`

**Comment by marcboulle** [comment]
Compléments à la  deprecation list
- `snb_predictor`
- `univariate_predictor_number`

Précisions:
- pour `discretization_method`et `grouping_method` en supervisé, toutes les valeurs sont deprecated, y compris `MOL`
-  pour `results_dir` et `results_prefix`,  il faudra gérer les utilisation existante de type directory, alors qu'en V11, un nom de directory sera interdit

Cf. https://github.com/KhiopsML/khiops/issues/223#top
- removed fields:
  -  "Selective Naive Bayes": trained, except if "Do data preparation only" is triggered 
  -  "Baseline predictor": never used in classification, always provided in regression
  -  "Number of univariate predictors": supressed

**Comment by popescu-v** [comment]
For `results_dir` and `results_prefix`: `KHIOPS_API_MODE` should be set to "true" when used via `khiops-python`, in which case the reports are stored in the current directory.

Hence, IMHO, there is no need for `report_file_path`, unless, of course, one chooses to set `KHIOPS_API_MODE` to "false", in which case we could specify a full absolute path to the report (otherwise, the report is stored in the training database directory). But this would add unnecessary complexity IMHO.
