### ISSUE TITLE
Support the new version of `khiops_env`

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/khiops-python#245]
#### Description
The `khiops_env` PR will land soon https://github.com/KhiopsML/khiops/pull/343. We should support the new features of `khiops_env` and its availability in the `conda` installation.

#### Questions/Ideas
- Make the conda detection use `khiops_env`
  - Conditional code?
- Support all the available variables in the new `khiops_env`
- "Deprecate" the old code

**Comment by popescu-v** [comment]
AFAIU, it would suffice to just initialize the relevant attributes of the `KhiopsLocalRunner` with the values of the appropriate environment variables, as sourced from `khiops_env`, irrespective of the environment. The new `khiops_env` now takes care of appropriately setting all relevant environment variables according to the execution environment (Conda, Conda-based, native), in a robust way, without (much) environment-conditional code.

**Comment by popescu-v** [comment]
Also, as the old code was not part of any official API, all deprecation mechanics would not be necessary IMHO; it would just suffice to remove that (environment-conditional) code.

**Comment by popescu-v** [comment]
> AFAIU, it would suffice to just initialize the relevant attributes of the `KhiopsLocalRunner` with the values of the appropriate environment variables, as sourced from `khiops_env`, irrespective of the environment. The new `khiops_env` now takes care of appropriately setting all relevant environment variables according to the execution environment (Conda, Conda-based, native), in a robust way, without (much) environment-conditional code.

There is one caveat though: we should allow users to override even the variables that are already set in the `khiops_env` script:
- source `khiops_env` variables into a specific data structure
- for each of these variables, if the variable is already in `os.environ`, use the value from the environment. Otherwise, use the `khiops_env`-defined value.

Thusly, current behavior whereby user-defined environment variables take precedence over default values (henceforth defined in `khiops_env`) is preserved.
